---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deploy-app.fullname" . }}-configmap
data:
    {{- with .Values.config.api }}
      react_app_server_url: {{ .host | quote }} 
    {{- end }}

