---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy-app.fullname" . }}-docker-registry-secret
data:
  .dockerconfigjson: {{ .Values.config.docker.jsonB64 | quote }}
type: kubernetes.io/dockerconfigjson