apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy-app.fullname" . }}-service
  labels:
    {{- include "deploy-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http-3001
  selector:
    {{- include "deploy-app.selectorLabels" . | nindent 4 }}
